import DashboardLayout from "@/components/DashboardLayout";
import InsightCard from "@/components/InsightCard";
import { useAiInsights, useRunAiAgent } from "@/hooks/usePlatformData";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Brain, Loader2, Sparkles, Filter } from "lucide-react";
import { useState } from "react";

export default function InsightsPage() {
  const [filter, setFilter] = useState<string | undefined>();
  const { data: insights, isLoading } = useAiInsights(filter);
  const aiAgent = useRunAiAgent();

  const categories = ["admin", "hr", "user", "licensing"];

  return (
    <DashboardLayout>
      <div className="p-6 space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="font-display text-2xl font-bold text-foreground">AI Intelligence Insights</h1>
            <p className="text-sm text-muted-foreground">Generated by the Platform Intelligence Agent</p>
          </div>
          <Button onClick={() => aiAgent.mutate()} disabled={aiAgent.isPending} size="lg" className="gap-2">
            {aiAgent.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Brain className="h-4 w-4" />}
            Run AI Agent
          </Button>
        </div>

        {aiAgent.isPending && (
          <Card className="border-primary/30 bg-primary/5">
            <CardContent className="flex items-center gap-3 py-4">
              <Loader2 className="h-5 w-5 animate-spin text-primary" />
              <div>
                <p className="font-medium text-sm">AI Agent Processing...</p>
                <p className="text-xs text-muted-foreground">Analyzing platform data, detecting patterns, generating insights</p>
              </div>
            </CardContent>
          </Card>
        )}

        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm flex items-center gap-2"><Filter className="h-4 w-4" /> Filter by Dashboard</CardTitle>
            </div>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              <Badge variant={!filter ? "default" : "outline"} className="cursor-pointer" onClick={() => setFilter(undefined)}>All</Badge>
              {categories.map(cat => (
                <Badge key={cat} variant={filter === cat ? "default" : "outline"} className="cursor-pointer capitalize" onClick={() => setFilter(cat)}>{cat}</Badge>
              ))}
            </div>
          </CardContent>
        </Card>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {isLoading ? (
            Array.from({ length: 4 }).map((_, i) => (
              <Card key={i} className="animate-pulse">
                <CardContent className="py-8">
                  <div className="h-4 w-3/4 bg-muted rounded mb-2" />
                  <div className="h-3 w-full bg-muted rounded mb-1" />
                  <div className="h-3 w-2/3 bg-muted rounded" />
                </CardContent>
              </Card>
            ))
          ) : insights && insights.length > 0 ? (
            insights.map((insight: any) => (
              <InsightCard
                key={insight.id}
                title={insight.title}
                summary={insight.summary}
                details={insight.details}
                category={insight.category}
                severity={insight.severity}
                dashboardTarget={insight.dashboard_target}
                isActionable={insight.is_actionable}
                createdAt={insight.created_at}
              />
            ))
          ) : (
            <Card className="md:col-span-2">
              <CardContent className="flex flex-col items-center justify-center py-12 text-center">
                <Sparkles className="h-10 w-10 text-muted-foreground mb-3" />
                <p className="font-medium">No insights yet</p>
                <p className="text-sm text-muted-foreground mt-1">Click "Run AI Agent" to generate intelligence insights</p>
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </DashboardLayout>
  );
}
